# Generated by Django 4.1.1 on 2022-10-11 05:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BDSA',
            fields=[
                ('cve_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='CVE-ID')),
                ('bdsa_id', models.CharField(max_length=50, unique=True, verbose_name='BDSA-ID')),
                ('title', models.TextField(max_length=500, verbose_name='Title')),
                ('added_date', models.DateTimeField(default=datetime.datetime.now)),
                ('json_file', models.FileField(blank=True, null=True, upload_to='json_files')),
            ],
        ),
    ]
