# Generated by Django 4.1.2 on 2022-10-25 04:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('QueryService', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bdsa',
            name='added_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
