# Generated by Django 4.1.1 on 2022-09-27 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QueryService', '0003_alter_bdsa_description_alter_bdsa_mitigation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bdsa',
            name='content',
            field=models.TextField(default=1, verbose_name='Content'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bdsa',
            name='bdsa_id',
            field=models.CharField(max_length=50, unique=True, verbose_name='BDSA-ID'),
        ),
    ]
