# Generated by Django 4.1.1 on 2022-09-28 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QueryService', '0004_bdsa_content_alter_bdsa_bdsa_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bdsa',
            name='id',
        ),
        migrations.AlterField(
            model_name='bdsa',
            name='cve_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='CVE-ID'),
        ),
    ]
