# Generated by Django 4.1.1 on 2022-10-04 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QueryService', '0007_bdsa_date_added'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bdsa',
            old_name='date_added',
            new_name='added_date',
        ),
    ]
