# Generated by Django 4.1.1 on 2022-10-04 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QueryService', '0010_bdsa_added_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bdsa',
            name='added_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
