# Generated by Django 4.1.1 on 2022-10-05 07:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QueryService', '0012_alter_bdsa_added_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bdsa',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
