# Generated by Django 4.1.1 on 2022-09-22 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QueryService', '0002_alter_bdsa_cve_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bdsa',
            name='description',
            field=models.TextField(max_length=500, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='bdsa',
            name='mitigation',
            field=models.CharField(blank=True, max_length=500, verbose_name='Mitigation'),
        ),
        migrations.AlterField(
            model_name='bdsa',
            name='patch_links',
            field=models.TextField(blank=True, max_length=500, verbose_name='Patch Links'),
        ),
        migrations.AlterField(
            model_name='bdsa',
            name='solution',
            field=models.TextField(blank=True, max_length=500, verbose_name='Solution'),
        ),
        migrations.AlterField(
            model_name='bdsa',
            name='technical_description',
            field=models.TextField(blank=True, max_length=500, verbose_name='Technical Description'),
        ),
        migrations.AlterField(
            model_name='bdsa',
            name='title',
            field=models.TextField(max_length=500, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='bdsa',
            name='vul_function',
            field=models.TextField(blank=True, max_length=500, verbose_name='Vulnerable Function'),
        ),
    ]
