# Generated by Django 4.1.1 on 2022-09-22 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BDSA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve_id', models.CharField(max_length=50, verbose_name='CVE-ID')),
                ('bdsa_id', models.CharField(max_length=50, verbose_name='BDSA-ID')),
                ('title', models.CharField(max_length=500, verbose_name='Title')),
                ('description', models.CharField(max_length=500, verbose_name='Description')),
                ('technical_description', models.CharField(max_length=500, verbose_name='Technical Description')),
                ('solution', models.CharField(max_length=500, verbose_name='Solution')),
                ('patch_links', models.TextField(max_length=500, verbose_name='Patch Links')),
                ('mitigation', models.CharField(max_length=500, verbose_name='Mitigation')),
                ('vul_function', models.CharField(max_length=500, verbose_name='Vulnerable Function')),
            ],
        ),
    ]
