# Generated by Django 4.1.1 on 2022-09-22 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QueryService', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bdsa',
            name='cve_id',
            field=models.CharField(max_length=50, unique=True, verbose_name='CVE-ID'),
        ),
    ]
